### ISSUE TITLE
clone java.util.Set with copy of relation

### ISSUE THREAD

**Issue by jboz** [nociar/jpa-cloner#19] opened 2015-02-24 17:36 UTC
Bug with equals/hasCode

My entities : 

	@Entity
	public class Product extends BaseEntity {

		@Id
		@Column(name = "PRODUCT_ID")
		@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ProductSequence")
		@SequenceGenerator(name = "ProductSequence")
		private Long id;

		@OneToMany(fetch = LAZY, cascade = ALL, orphanRemoval = true)
		@JoinColumn(name = "PRODUCT_ID")
		private Set<ProductProperty> generalProperties = new HashSet<ProductProperty>();

		[...]
	}

	@Entity
	public abstract class ProductProperty extends BaseEntity {

		@Id
		@Column(name = "PRODUCT_PROPERTY_ID")
		@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ProductPropertySequence")
		@SequenceGenerator(name = "ProductPropertySequence")
		private Long id;

		@ManyToOne
		@JoinColumn(name = "PROPERTY_ID")
		private Property property;

		@ManyToOne
		@JoinColumn(name = "PRODUCT_ID")
		private Product product;

		@Column
		private String value;
	}

	@MappedSuperclass
	public abstract class BaseEntity implements Entity {

		[...]

		public abstract Serializable getId();

		@Override
		public boolean equals(final Object obj) {
			if (obj == null || !(getClass().isInstance(obj))) {
				return false;
			}
			if (this == obj) {
				return true;
			}
			final BaseEntity other = (BaseEntity) obj;
	
			if (getId() != null) {
				return getId().equals(other.getId());
			} else if (getId() == null && other.getId() != null) {
				return false;
			}
	
			// other fields
			return EqualsBuilder.reflectionEquals(this, obj);
		}

		@Override
		public int hashCode() {
			return new HashCodeBuilder().append(getId()).toHashCode();
		}
	}

I want to do :

	Product product = new Product();
	product.addProperty(propertyA, "value"); // utility method
	product.addProperty(propertyB, "value");
	product = entityManager.merge(product);
	Product clone = JpaCloner.clone(product, PropertyFilters.getAnnotationFilter(GeneratedValue.class, Transient.class, Version.class), "+*");
	[...]

My product contains 2 ProductProperty with same value. 
My cloned product contains only 1 ProductProperty !

I think it's due to this lines of code (JpaCloner) : 

	protected void explore(Object entity, String property, Collection<?> collection) {
		[...]
		for (Object o : collection) {
			clonedCollection.add(getClone(o));
		}
		[...]
	}

getClone(o) don't copy @ManyToOne relation before store to clonedCollection set.
So next clonedCollection.add will not add another clone of ProductProperty.

How to make it work ?

Thanks.

**Comment by nociar** [comment] 2015-02-24 20:33
Hello, your code seems to be OK. But I have doubts regarding the BaseEntity#equals.
It seems that the method compares object properties if both objects have NULL IDs. This may easily cause that two different objects are equal. May be this is the reason why the cloned relation contais only one object instead of two. 

Could you please check the equal method for both properties before cloning?

**Comment by nociar** [comment] 2015-02-25 08:37
UPDATE: I am pretty sure that the problem is related to the implementation of BaseEntity#equals. The cloning of the ProductProperty class is a multi-step process:

1. Create a new instance of the ProductProperty class.
2. Copy all basic fields: ProductProperty#id & ProductProperty#value.
3. Put in the java.util.Set collection.
4. Clone relation fields: ProductProperty#property.

The problem is the step 3. ProductProperty contains NULL reference for the "property" field when inserted into the java.util.Set. I will think about changes in the JPA cloner internals regarding this issues.

Meantime, I suggest you to change the last line of the equals as:
**return false;**

**Comment by jboz** [comment] 2015-02-25 14:49
Thanks for you responses. I have modify my equals in consequence : 

	if (getProperty() == null && getProduct() == null && other.getProperty() == null && other.getProduct() == null) {
		// if no product and no property are defined, objects identity cannot be defined
		return false;
	}
	// equals sur les autres champs
	return EqualsBuilder.reflectionEquals(this, obj);

In that way my other code is not impacted because property and product attributs are never absent in the rest of my application.

**Comment by nociar** [comment] 2015-04-19 17:52
Resolved in v1.0.3. *ToMany relations are cloned after *ToOne relations. This means that hashCode and equals will be called after singular relations are cloned.

**Closed by nociar** 2015-04-19 17:52 UTC
